name: 🔃 Update article lists

on:
  schedule:
    - cron:  '0 1,13 * * *'

jobs:
  update-list:
      runs-on: ubuntu-latest
      steps:
        - name: set up
          uses: actions/setup-go@v2

        - name: pull src
          uses: actions/checkout@v2

        - name: run script
          run: go run ./scripts/update_list/main.go