name: 🔃 Update Contents

on:
  schedule:
    - cron:  '* 1,13 * * *'
  push:
    branches:
      - master
    paths:
      - 'scripts/content_updater/**'
      - '.github/workflows/update.yml'

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: set up golang
          uses: actions/setup-go@v2
          with:
            go-version: ^1.17

        - name: checkout src
          uses: actions/checkout@v2

        - name: test src
          run : go test -v ./...
          working-directory: ./scripts/content_updater

  update-list:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: set up golang
          uses: actions/setup-go@v2
          with:
            go-version: ^1.17

        - name: checkout src
          uses: actions/checkout@v2

        - name: run script
          env:
            HATENA_ID: ${{ secrets.HATENA_ID }}
            HATENA_BLOG_ID: ${{ secrets.HATENA_BLOG_ID }}
            HATENA_USER_NAME: ${{ secrets.HATENA_USER_NAME }}
            HATENA_PASSWORD: ${{ secrets.HATENA_PASSSWORD }}
          run: |
            go mod download
            go run main.go
          working-directory: ./scripts/content_updater

        - name: commit and push src
          run: |
            git config --local user.email "auto-deploy"
            git config --local user.name "auto-deploy"
            git add --all
            git commit -m "update contents"
            git push origin master