name: 🔃 Update Contents

on:
  schedule:
    - cron:  '* 13 * * *'
  push:
    branches:
      - master
    paths:
      - 'scripts/content_updater/**'
      - '.github/workflows/update.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: checkout src
        uses: actions/checkout@v2

      - name: build src
        run : go build
        working-directory: ./scripts/content_updater

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: checkout src
        uses: actions/checkout@v2

      - name: lint src
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: checkout src
        uses: actions/checkout@v2

      - name: test src
        run : go test -v ./...
        working-directory: ./scripts/content_updater

  update-list:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: checkout src
        uses: actions/checkout@v2

      - name: run script
        env:
          HATENA_ID: ${{ secrets.HATENA_ID }}
          HATENA_BLOG_ID: ${{ secrets.HATENA_BLOG_ID }}
          HATENA_USER_ID: ${{ secrets.HATENA_USER_ID }}
          HATENA_PASSWORD: ${{ secrets.HATENA_PASSSWORD }}
        run: |
          go mod download
          go run *.go
        working-directory: ./scripts/content_updater

      - name: commit and push src
        run: |
          git config --local user.email "auto-deploy"
          git config --local user.name "auto-deploy"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add --all
            git commit -m "update contents"
            git push origin master
          fi